/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.ThongKeLichHop;


import javax.swing.JFrame;



/**
 *
 * @author huuph
 */
public class ThongKe extends javax.swing.JPanel {
//    private ThongKeLichHopController controller;
    private JFrame parentJFrame;
////    private JPanel view = new JPanel();
    /**
     * Creates new form ThongKe
     * @param parentFrame
     */
    public ThongKe(JFrame parentFrame) {
        this.parentJFrame = parentFrame;
        initComponents();
//        controller = new ThongKeLichHopController(ThongKeThamGiaBtn,ThongKeThongTinBtn);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThongKeThongTinBtn = new javax.swing.JButton();
        ThongKeThamGiaBtn = new javax.swing.JButton();

        ThongKeThongTinBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ThongKeThongTinBtn.setText("Thống kê thông tin các cuộc họp");
        ThongKeThongTinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongKeThongTinBtnActionPerformed(evt);
            }
        });

        ThongKeThamGiaBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ThongKeThamGiaBtn.setText("Thống kê tham gia của các hộ gia đình");
        ThongKeThamGiaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongKeThamGiaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ThongKeThongTinBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ThongKeThamGiaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(ThongKeThongTinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(ThongKeThamGiaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ThongKeThongTinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongKeThongTinBtnActionPerformed
        // TODO add your handling code here:
        ThongKeThongTin thongKeThongTin =  new ThongKeThongTin();
//        this.getContainerListeners().setLayout(thongKeThongTin);
        thongKeThongTin.setLocationRelativeTo(null);
        thongKeThongTin.setResizable(true);
        thongKeThongTin.setVisible(true);
    }//GEN-LAST:event_ThongKeThongTinBtnActionPerformed

    private void ThongKeThamGiaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongKeThamGiaBtnActionPerformed
        // TODO add your handling code here:
    
        ThongKeThamGia thongKeThamGia =  new ThongKeThamGia();
        thongKeThamGia.setLocationRelativeTo(null);
        thongKeThamGia.setResizable(true);
        thongKeThamGia.setVisible(true);
    }//GEN-LAST:event_ThongKeThamGiaBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ThongKeThamGiaBtn;
    private javax.swing.JButton ThongKeThongTinBtn;
    // End of variables declaration//GEN-END:variables
}